# tomcat configuration
server:
  port: 8080
  servlet:
    session:
      timeout: 300m # session会话超时时间，默认情况 下是30分钟（m）,不能小于1分钟
      cookie:
        name: JSESSIONID # 指定浏览器Cookie中关于SessionID保存的那个名称



# mybatis configuration
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
    default-scripting-language:

# database configuration
spring.datasource: 
  url: jdbc:mysql://localhost:3306/myappdb?serverTimezone=GMT%2B8
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver
# dev/release
spring.profiles.active: dev
#spring.profiles.active: prd


spring.application.name: myapp


